/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'FW_AO2024_Cpu_MeterSystem_Meter_1261_v01' 
 * Target:  'FW_AO2024_Cpu_MeterSystem_Meter_1261_v01' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "NUC1261.h"



#endif /* RTE_COMPONENTS_H */
